### ISSUE TITLE
limits bug

### ISSUE THREAD

**Issue by scottscreations** [scalia/sphinxsearch#18]
I think this is a bug at least, i have sorting my data by most recent entries (date field). I got it working right, as soon as i put in the ->limit(200) my data is no longer the recent stuff. It loses its sorting. I can provide screenshots of the results if needed.

        $results = SphinxSearch::search("pam_unix", "ninjalogs")
            ->setFieldWeights(array('devicereportedtime' => 10))
            ->limit(200)
            ->setMatchMode(\Sphinx\SphinxClient::SPH_MATCH_ANY)
            ->setSortMode(\Sphinx\SphinxClient::SPH_SORT_ATTR_DESC, 'devicereportedtime')
            ->get(true);

I temporarily added this line to sphinxsearch.php and took out my ->limit(200) and it worked properly.

      $this->_connection->setLimits(0, 200, 200, 0);

I am not sure why its not taking the 200 and using it properly. 

Any ideas?

**Comment by dvigueras** [comment]
Sorry, this package is unmaintained and therefore we won't review more issues, for Laravel 5 support use https://github.com/sngrl/sphinxsearch
