### ISSUE TITLE
Non-default DB Settings

### ISSUE THREAD

**Issue by swvjeff** [scalia/sphinxsearch#28]
Is it possible to use non-default DB settings for querying my Sphinx DB? I'd like to store my Sphinx records in a completely separate database than my main Laravel site, but it looks like this isn't supported by SphinxSearch. Maybe I'm missing something? If not, are there any plans to add support for this feature?

**Comment by dvigueras** [comment]
Sorry, this package is unmaintained and therefore we won't review more issues, for Laravel 5 support use https://github.com/sngrl/sphinxsearch
