### ISSUE TITLE
Remove int casting from filter function in SphinxSearch

### ISSUE THREAD

**Issue by avnil007** [scalia/sphinxsearch#30]
Hi ,

Please remove int casting from filter function line 102 and 107

In my case i need to filter by string value , as you know it's impossible in the sphinx so i creating numeric checksum value 
Please look for example in  
http://stackoverflow.com/questions/5736037/create-a-filter-in-sphinx-with-text-string-value

function 

 public static function crc32($val){
        $checksum = crc32($val);
        if($checksum < 0) $checksum += 4294967296;
        return $checksum;
    }

But there is some issue in windows 64 bit and PHP with integer size (Mysql work as expected) .
Because of the int issue in windows some time i receiving negative value from crc32 and then i add 4294967296  to return value  to convert it back to positive integer in some cases the result is double type (again because integer issue in windows) and then the cast to int return checksum back to negative value  and fake the search result.

**Comment by dvigueras** [comment]
Sorry, this package is unmaintained and therefore we won't review more issues, for Laravel 5 support use https://github.com/sngrl/sphinxsearch
