### ISSUE TITLE
Highlight searched words

### ISSUE THREAD

**Issue by ndamnjanovic** [scalia/sphinxsearch#37]
Is there a way to highlight words within documents that met criteria? 

http://stackoverflow.com/questions/26463390/get-excerpt-around-search-word

**Comment by aEscarcha** [comment]
There is a pull request on this, let's hope that they will merge it soon.

https://github.com/scalia/sphinxsearch/pull/31

**Comment by dvigueras** [comment]
Sorry, this package is unmaintained and therefore we won't review more issues, for Laravel 5 support use https://github.com/sngrl/sphinxsearch
