### ISSUE TITLE
No support for dynamic attributes?

### ISSUE THREAD

**Issue by stackoverflows** [scalia/sphinxsearch#38]
Assume the following line 
$result = SphinxSearch::search(Input::get('query'))->get();

(where the underlying model is called Product). If in the Product name you have a dynamic attribute set with getXXXAttribute() such as $product->final_price (which would be created via a getFinalPriceAttribute() method), then that attribute will NOT be created for that object. That is, $product->final_price will not exist for results returned from SphinxSearch. I'm running the latest dev-master.

**Comment by dvigueras** [comment]
Sorry, this package is unmaintained and therefore we won't review more issues, for Laravel 5 support use https://github.com/sngrl/sphinxsearch
