### ISSUE TITLE
No Id Column Table

### ISSUE THREAD

**Issue by lsxhope** [scalia/sphinxsearch#48]
i have find a bug and fix it , the id was fixed.
![qq 20150515184433](https://cloud.githubusercontent.com/assets/5173240/7651660/7d722952-fb35-11e4-9a20-984aed828582.png)

**Comment by dvigueras** [comment]
Sorry, this package is unmaintained and therefore we won't review more issues, for Laravel 5 support use https://github.com/sngrl/sphinxsearch
