### ISSUE TITLE
lavarel 5 ? 

### ISSUE THREAD

**Issue by LxiaoGirl** [scalia/sphinxsearch#49]
The author whether to increase support for laravel5 ?

**Comment by sngrl** [comment]
I subscribe to the issue.

**Comment by brmn** [comment]
+1

**Comment by jhuliano** [comment]
There is a PR by @ismaGNU with Laravel 5 support, see https://github.com/ismaGNU/sphinxsearch/ it worked wonders for me.

**Comment by noprobz09** [comment]
+1

**Comment by dvigueras** [comment]
This package is unmaintained, for Laravel 5 support use https://github.com/sngrl/sphinxsearch
