### ISSUE TITLE
How to use sphinx search?

### ISSUE THREAD

**Issue by umka05** [scalia/sphinxsearch#7]
return array (
    'host'    => '127.0.0.1',
    'port'    => 9312,
    'indexes' => array (
        'my_index_name' => array ( 'table' => '???', 'column' => '??' ),
    )
);

$results = SphinxSearch::search('?', '?')
    ->limit(30)
    ->filter('?', ?)
    ->range('?', ?)
    ->get();

what are where you insert?
How it works?

**Comment by dvigueras** [comment]
Sorry, this package is unmaintained and therefore we won't review more issues, for Laravel 5 support use https://github.com/sngrl/sphinxsearch
